plugins {
    id("maven-publish")
    id("signing")
    id("net.fabricmc.fabric-loom") version("1.17.12")
    id("me.modmuss50.mod-publish-plugin") version("2.1.1")
    id("com.kotori316.plugin.cf").version("4.0")
}

base {
    archivesName = "${project.baseName}-Fabric-${project.minecraftVersion}"
}
version = project.modVersion
group = "com.kotori316"

println("Java: " + System.getProperty("java.version") +
        " JVM: " + System.getProperty("java.vm.version") +
        "(" + System.getProperty("java.vendor") + ")" +
        " Arch: " + System.getProperty("os.arch"))

loom {
    runs {
        named("client") {
            configName = "Client"
            runDir = "run"
        }
        create("gameTestServer") {
            configName = "GameTestServer"
            server()
            //noinspection SpellCheckingInspection
            vmArgs(
                    "-ea",
                    "-Dfabric-api.gametest",
                    "-Dfabric-api.gametest.report-file=game_test/test-results/test/game_test.xml"
            )
            runDir = "run-server"
            source(sourceSets.getAt("test"))
        }
    }
}

repositories {
    maven {
        name = "Kotori316 Plugin"
        url = uri("https://maven.kotori316.com/")
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraftVersion}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    compileOnly(project(":common"))

    // Fabric API. This is technically optional, but you probably want it anyway.
    implementation("net.fabricmc.fabric-api:fabric-api:${project.fabric_version}")

    implementation("com.kotori316:VersionCheckerMod:${project.property("automatic_potato_version")}") {
        transitive = false
    }
    implementation("com.kotori316:debug-utility-fabric:${project.property("debug_util_version")}")

    testImplementation(project(":common"))
}

processResources {
    from project(":common").sourceSets.main.resources
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand([
                "version"  : project.version,
                "mcVersion": project.property("minecraftVersion"),
        ])
    }
}

// ensure that the encoding is set to UTF-8, no matter what the system default is
// this fixes some edge cases with special characters not displaying correctly
// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    source(project(":common").sourceSets.main.allSource)
}

test {
    // Files in test are GameTest, so the test task do nothing.
    failOnNoDiscoveredTests = false
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

publishMods {
    dryRun = !Boolean.parseBoolean(project.releaseMode)
    type = STABLE
    file = tasks.jar.archiveFile
    additionalFiles.from(tasks.named("sourcesJar"))
    modLoaders.add("fabric")
    displayName = "${project.version}-fabric"
    changelog = "For Minecraft ${project.minecraftVersion} with Fabric ${project.fabric_version}"

    curseforge {
        accessToken = (project.findProperty("curseforge_additional-enchanted-miner_key") ?: System.getenv("CURSE_TOKEN") ?: "") as String
        projectId = project.curseforge_id
        minecraftVersions.add(project.minecraftVersion)
        requires("automatic-potato")
    }

    modrinth {
        accessToken = (project.findProperty("modrinthToken") ?: System.getenv("MODRINTH_TOKEN") ?: "") as String
        projectId = project.modrinth_id
        minecraftVersions.add(project.minecraftVersion)
        requires("automatic-potato")
    }
}

publishing {
    if (Boolean.parseBoolean(project.releaseMode)) {
        repositories {
            def u = project.findProperty("maven_username") as String ?: System.getenv("MAVEN_USERNAME") ?: ""
            def p = project.findProperty("maven_password") as String ?: System.getenv("MAVEN_PASSWORD") ?: ""
            if (u != "" && p != "") {
                maven {
                    name = "kotori316-maven"
                    // For users: Use https://maven.kotori316.com to get artifacts
                    url = uri("https://maven2.kotori316.com/production/maven")
                    credentials {
                        username = u
                        password = p
                    }
                }
            }
        }
    }
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.base.archivesName.get().toLowerCase()
            from components.java
            pom {
                name = project.base.archivesName.get()
                description = "AutoPlanter for Minecraft ${project.minecraftVersion} and Fabric ${project.fabric_version}"
                url = "https://github.com/Kotori316/AutoPlanter"
                packaging = "jar"
            }
        }
    }
}

jar.finalizedBy("jksSignJar")

tasks.register("jksSignJar") {
    dependsOn("jar")
    boolean executeCondition = (System.getenv("SIGN_KEY_ALIAS") || project.hasProperty("jarSign.keyAlias")) &&
            (System.getenv("SIGN_KEY_LOCATION") || project.hasProperty("jarSign.keyLocation")) &&
            (System.getenv("SIGN_STORE_PASS") || project.hasProperty("jarSign.storePass"))
    onlyIf { executeCondition }
    doLast {
        //noinspection HttpUrlsUsage
        ant.signjar(
                jar: jar.archiveFile.get(),
                alias: System.getenv("SIGN_KEY_ALIAS") ?: project.findProperty("jarSign.keyAlias") ?: "",
                keystore: System.getenv("SIGN_KEY_LOCATION") ?: project.findProperty("jarSign.keyLocation") ?: "",
                storepass: System.getenv("SIGN_STORE_PASS") ?: project.findProperty("jarSign.storePass") ?: "",
                sigalg: "Ed25519",
                digestalg: "SHA-256",
                tsaurl: "http://timestamp.digicert.com",
        )
    }
}

if (!project.hasProperty("signing.keyId") && System.getenv("SIGNING_KEY_ID")) {
    ext["signing.keyId"] = System.getenv("SIGNING_KEY_ID")
}
if (!project.hasProperty("signing.password") && System.getenv("SIGNING_PASSWORD")) {
    ext["signing.password"] = System.getenv("SIGNING_PASSWORD")
}
if (!project.hasProperty("signing.secretKeyRingFile") && System.getenv("SIGNING_SECRET_KEY_RING_FILE")) {
    ext["signing.secretKeyRingFile"] = System.getenv("SIGNING_SECRET_KEY_RING_FILE")
}

signing {
    sign(publishing.publications)
}

boolean hasGpgSignature = project.hasProperty("signing.keyId") &&
        project.hasProperty("signing.password") &&
        project.hasProperty("signing.secretKeyRingFile")

tasks.withType(Sign).configureEach {
    it.onlyIf {
        hasGpgSignature
    }
}

import com.kotori316.plugin.cf.CallVersionCheckFunctionTask
import com.kotori316.plugin.cf.CallVersionFunctionTask

tasks.register("registerVersion", CallVersionFunctionTask.class) {
    functionEndpoint = readVersionFunctionEndpoint(project)
    gameVersion = project.findProperty("minecraftVersion") as String
    platform = "fabric"
    platformVersion = project.findProperty("fabric_version") as String
    modName = project.findProperty("mod_id") as String
    changelog = "For ${project.findProperty("minecraftVersion")}"
    homepage = "https://modrinth.com/mod/auto-planter"
}

tasks.register("checkReleaseVersion", CallVersionCheckFunctionTask.class) {
    gameVersion = project.findProperty("minecraftVersion") as String
    platform = "fabric"
    modName = project.findProperty("mod_id") as String
    version = project.version
    failIfExists = Boolean.parseBoolean(System.getenv("FAIL_IF_EXISTS"))
}
