import com.kotori316.plugin.cf.CallVersionCheckFunctionTask
import com.kotori316.plugin.cf.CallVersionFunctionTask

import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter

plugins {
    id("maven-publish")
    id("signing")
    id("java")
    id("net.minecraftforge.gradle") version("7.0.32")
    id("me.modmuss50.mod-publish-plugin") version("2.2.0")
    id("com.kotori316.plugin.cf").version("4.0")
}

version = project.modVersion
group = "com.kotori316" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
base {
    archivesName = "${project.baseName}-Forge-${project.minecraftVersion}"
}
java.toolchain.languageVersion = JavaLanguageVersion.of(25)
java.withSourcesJar()

println("Java: " + System.getProperty("java.version") +
        " JVM: " + System.getProperty("java.vm.version") +
        "(" + System.getProperty("java.vendor") + ")" +
        " Arch: " + System.getProperty("os.arch"))

minecraft {
    // Default run configurations.
    // These can be tweaked, removed, or duplicated as needed.
    runs {
        configureEach {
            workingDir.convention(layout.projectDirectory.dir("run"))
            systemProperty("forge.logging.markers", "")
            systemProperty("forge.logging.console.level", "debug")
            systemProperty("eventbus.api.strictRuntimeChecks", "true")
            systemProperty("mixin.debug.export", "true")
            systemProperty("terminal.ansi", "true")
            if (System.getProperty("os.name").startsWith("Mac")) {
                jvmArgs("-XstartOnFirstThread")
            }
        }

        register("client") {
        }

        register("server") {
        }

        register("data") {
            args "--mod", project.mod_id, "--all", "--output", layout.projectDirectory.dir("src/generated/resources/"), "--existing", layout.projectDirectory.dir("src/main/resources")
        }
    }
}

processResources {
    from project(":common").sourceSets.main.resources
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    inputs.property("version", project.version)
    inputs.property("mcVersion", project.property("minecraftVersion"))

    ["fabric.mod.json", "META-INF/mods.toml", "META-INF/neoforge.mods.toml"].forEach { fileName ->
        filesMatching(fileName) {
            expand([
                    "version"  : project.version,
                    "mcVersion": project.property("minecraftVersion"),
            ])
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven(fg.forgeMaven)
    maven(fg.minecraftLibsMaven)
    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge'
                url = 'https://repo.spongepowered.org/repository/maven-public'
            }
        }
        filter {
            includeGroupAndSubgroups('org.spongepowered')
        }
    }
}

dependencies {
    implementation(minecraft.dependency("net.minecraftforge:forge:${project.forgeVersion}"))
    compileOnly(project(":common"))
    annotationProcessor("net.minecraftforge:eventbus-validator:7.0.5")
}

tasks.withType(JavaCompile).configureEach {
    source(project(":common").sourceSets.main.allSource)
}

// Example for how to get properties into the manifest for reading by the runtime..
jar {
    String vendor = "Kotori316"
    manifest {
        attributes([
                "Specification-Title"     : project.name,
                "Specification-Vendor"    : vendor,
                "Specification-Version"   : "1", // We are version 1 of ourselves
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.version.toString(),
                "Implementation-Vendor"   : vendor,
                "Implementation-Timestamp": ZonedDateTime.now().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME),
                "MixinConfigs"            : "${project.mod_id}.mixins.json",
                "Automatic-Module-Name"   : project.mod_id,
        ])
    }
}

jar.finalizedBy("jksSignJar")

tasks.register("jksSignJar") {
    dependsOn("jar")
    boolean executeCondition = (System.getenv("SIGN_KEY_ALIAS") || project.hasProperty("jarSign.keyAlias")) &&
            (System.getenv("SIGN_KEY_LOCATION") || project.hasProperty("jarSign.keyLocation")) &&
            (System.getenv("SIGN_STORE_PASS") || project.hasProperty("jarSign.storePass"))
    onlyIf { executeCondition }
    doLast {
        //noinspection HttpUrlsUsage
        ant.signjar(
                jar: jar.archiveFile.get(),
                alias: System.getenv("SIGN_KEY_ALIAS") ?: project.findProperty("jarSign.keyAlias") ?: "",
                keystore: System.getenv("SIGN_KEY_LOCATION") ?: project.findProperty("jarSign.keyLocation") ?: "",
                storepass: System.getenv("SIGN_STORE_PASS") ?: project.findProperty("jarSign.storePass") ?: "",
                sigalg: "Ed25519",
                digestalg: "SHA-256",
                tsaurl: "http://timestamp.digicert.com",
        )
    }
}

publishMods {
    dryRun = !Boolean.parseBoolean(project.releaseMode)
    type = STABLE
    file = tasks.jar.archiveFile
    additionalFiles.from(tasks.named("sourcesJar"))
    modLoaders.add("forge")
    displayName = "${project.version}-forge"
    changelog = "For Minecraft ${project.minecraftVersion} with Forge ${project.forgeVersion}"

    curseforge {
        accessToken = (project.findProperty("curseforge_additional-enchanted-miner_key") ?: System.getenv("CURSE_TOKEN") ?: "") as String
        projectId = project.curseforge_id
        minecraftVersions.add(project.minecraftVersion)
        server = true
        client = true
    }

    modrinth {
        accessToken = (project.findProperty("modrinthToken") ?: System.getenv("MODRINTH_TOKEN") ?: "") as String
        projectId = project.modrinth_id
        minecraftVersions.add(project.minecraftVersion)
    }
}

publishing {
    if (Boolean.parseBoolean(project.releaseMode)) {
        repositories {
            def u = project.findProperty("maven_username") as String ?: System.getenv("MAVEN_USERNAME") ?: ""
            def p = project.findProperty("maven_password") as String ?: System.getenv("MAVEN_PASSWORD") ?: ""
            if (u != "" && p != "") {
                maven {
                    name = "kotori316-maven"
                    // For users: Use https://maven.kotori316.com to get artifacts
                    url = uri("https://maven2.kotori316.com/production/maven")
                    credentials {
                        username = u
                        password = p
                    }
                }
            }
        }
    }
    publications {
        mavenJava(MavenPublication) {
            artifactId = project.base.archivesName.get().toLowerCase()
            from components.java
            pom {
                name = project.base.archivesName.get()
                description = "AutoPlanter for Minecraft ${project.minecraftVersion} and Forge ${project.forgeVersion}"
                url = "https://github.com/Kotori316/AutoPlanter"
                packaging = "jar"
            }
        }
    }
}

if (!project.hasProperty("signing.keyId") && System.getenv("SIGNING_KEY_ID")) {
    ext["signing.keyId"] = System.getenv("SIGNING_KEY_ID")
}
if (!project.hasProperty("signing.password") && System.getenv("SIGNING_PASSWORD")) {
    ext["signing.password"] = System.getenv("SIGNING_PASSWORD")
}
if (!project.hasProperty("signing.secretKeyRingFile") && System.getenv("SIGNING_SECRET_KEY_RING_FILE")) {
    ext["signing.secretKeyRingFile"] = System.getenv("SIGNING_SECRET_KEY_RING_FILE")
}

signing {
    sign(publishing.publications)
}

boolean hasGpgSignature = project.hasProperty("signing.keyId") &&
        project.hasProperty("signing.password") &&
        project.hasProperty("signing.secretKeyRingFile")

tasks.withType(Sign).configureEach {
    it.onlyIf {
        hasGpgSignature
    }
}

test {
    // Files in test are GameTest, so the test task do nothing.
    failOnNoDiscoveredTests = false
}

tasks.register("registerVersion", CallVersionFunctionTask.class) {
    functionEndpoint = readVersionFunctionEndpoint(project)
    gameVersion = project.findProperty("minecraftVersion")
    platform = "forge"
    platformVersion = project.findProperty("forgeVersion") as String
    modName = project.findProperty("mod_id")
    changelog = "For ${project.findProperty("minecraftVersion")}"
    homepage = "https://www.curseforge.com/minecraft/mc-mods/planting-dirt-for-saplings"
}

tasks.register("checkReleaseVersion", CallVersionCheckFunctionTask.class) {
    gameVersion = project.findProperty("minecraftVersion")
    platform = "forge"
    modName = project.findProperty("mod_id")
    version = project.version
    failIfExists = Boolean.parseBoolean(System.getenv("FAIL_IF_EXISTS"))
}

// Merge the resources and classes into the same directory.
// This is done because java expects modules to be in a single directory.
// And if we have it in multiple we have to do performance intensive hacks like having the UnionFileSystem
// This will eventually be migrated to ForgeGradle so modders don't need to manually do it. But that is later.
sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}
