plugins {
    id "java"
    id "org.spongepowered.gradle.vanilla" version "0.3.2"
}

base {
    archivesName = "${project.baseName}-Common-${project.minecraftVersion}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

minecraft {
    version(project.minecraftVersion)
}

dependencies {
    compileOnly("org.spongepowered:mixin:0.8.7")
    implementation("com.google.code.findbugs:jsr305:3.0.2")
}
