modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Kotori316/AutoPlanter/issues/"
license = "All Rights Reserved."
[[mods]]
modId = "auto_planter"
version = "${version}"
displayName = "Auto Planter"
updateJSONURL = "https://version.kotori316.com/get-version/${mcVersion}/neoforge/auto_planter"
credits = "Saplings"
authors = "Kotori316"
description = '''
Auto Planter
'''
[[mixins]]
config = "auto_planter.mixins.json"
[[dependencies.auto_planter]]
modId = "neoforge"
type = "required"
versionRange = "[20.6.0-beta,)"
ordering = "NONE"
side = "BOTH"
